### ISSUE TITLE
30% gefüllt trotz Leerlauf

### ISSUE THREAD

**Issue by HuliganLPR** [MakeMagazinDE/Zisternensensor#1]
Hallo Make und danke Wolfgang Neußer für den Artikel.

Leider habe ich festgestellt, dass im "Leerlauf" sprich ohne angeschlossenem Druckschlauch oder/und damit auch bei komplett leerer Zisterne. Bei mir wieder ein Füllstand von 15-30% bei den Messungen ausgegeben wird.

**Comment by BeaconLE** [comment]
Hallo HuliganLPR, 
deine Messwerte ohne angeschlossenen Messschlauch kann ich nicht verstehen. Bei mir werden in so einem Fall 1% angezeigt, das liegt im Toleranzbereich. Wie sehen denn die Werte bei unterschiedlichen Füllständen aus? Sind die einigermaßen realistisch? Wenn nicht liegt ein generelles Problem vor.

Wolfgang

**Comment by HuliganLPR** [comment]
Hallo Wolfgang,

ich habe eben nochmal das "Setup" geändert und meine Schlauchführung geändert. Der Sensor sitzt jetzt nicht mehr zwischen Pumpe und Ventil. Nach dem Ventil war der Abgang der Zisterne.
Sondern jetzt als letztes in der Kette. Sprich Pumpe -> Ventil -> Sensor -> Abgang. Jetzt stimmen die Messwerte. 
Die Wartezeit zwischen Druckaufbau und Messung war einfach zu gering in meinem Aufbau. Vermutlich wegen dem zu geringen Durchlass meiner T-Stücke im Schlauch, der Messwert wurde erhoben bevor sich der Druck abbauen konnte. Das Problem konnte ich auf beiden Wegen lösen (Anpassung der Karenzzeit und/oder Umbau). Habe mich aber letztentlich für den Umbau entschieden. 
Nachmal vielen Dank für die Idee und den BasisCode. Sehr schönes und spannendes Projekt.

**Comment by MakeMagazinDE** [comment]
Danke!
